name: watchtower

services:
  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
    command: --cleanup --interval=1800
