name: lucky

services:
  lucky:
    image: gdy666/lucky:v2
    container_name: lucky
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/lucky:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: host
